Admin.create!([
  {fname: "Sample", lname: "Admin", username: nil, email: "admin@admin.com", password: "password", super_admin: false, full_name: "Sample Admin", active: true}
])
Member.create!([
  {fname: "George", lname: "Williams", email: "george@williams.com", password_digest: "$2a$10$D0zvp/5kCfOy9N8AnURs.Ov/yj0c5Vnl984dSFlq2lPLWj/h9eWsm", address_line1: "100 Woods Ln", address_line2: "", city: "Wayne", state: "PA", zip: "19087", primaryEC_fname: "Jeff", primaryEC_lname: "Williams", primaryEC_relationship: "Son", secondaryEC_fname: "", secondaryEC_lname: "", secondaryEC_relationship: "", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "Q", phone: "(234) 723-4872", primaryEC_phone: "(238) 472-9384", secondaryEC_phone: "", tertiaryEC_phone: nil, cell: "(922) 342-3434", primaryEC_cell: "(234) 234-2342", secondaryEC_cell: "", tertiaryEC_cell: nil, full_name: "George Q Williams", confirmed: true},
  {fname: "John", lname: "Smith", email: "john@smith.com", password_digest: "$2a$10$3uKDVqhIj5Q86SObreTj3OkT/kYI4ON5vnRN7asPcy5t1OhJeljcW", address_line1: "416 St Davids Rd", address_line2: "", city: "Wayne", state: "PA", zip: "19087", primaryEC_fname: "Jane", primaryEC_lname: "Smith", primaryEC_relationship: "Spouse", secondaryEC_fname: "", secondaryEC_lname: "", secondaryEC_relationship: "", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "D", phone: "(723) 984-7329", primaryEC_phone: "(239) 847-2394", secondaryEC_phone: "", tertiaryEC_phone: nil, cell: "(623) 498-1303", primaryEC_cell: "(897) 982-3723", secondaryEC_cell: "", tertiaryEC_cell: nil, full_name: "John D Smith", confirmed: true},
  {fname: "Paul", lname: "Jones", email: "paul@jones.com", password_digest: "$2a$10$oz43KwRSLOy3Qq46rYEB2er2Ww8gvw1Dv5WXBaM/1NP5B37vb2FKO", address_line1: "233 Highland Ave", address_line2: "", city: "Devon", state: "PA", zip: "19333", primaryEC_fname: "Rose", primaryEC_lname: "Jones", primaryEC_relationship: "Daughter", secondaryEC_fname: "", secondaryEC_lname: "", secondaryEC_relationship: "", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "F", phone: "(897) 239-8792", primaryEC_phone: "(238) 979-8237", secondaryEC_phone: "", tertiaryEC_phone: nil, cell: "(234) 782-3642", primaryEC_cell: "(923) 847-2394", secondaryEC_cell: "", tertiaryEC_cell: nil, full_name: "Paul F Jones", confirmed: true},
  {fname: "Betty", lname: "Johnson", email: "betty@johnson.com", password_digest: "$2a$10$jRDMbC5NXFNniX740QxLJurdB.ySFLzg4KsyFYG4qtqi8WDYRt3am", address_line1: "213 Spencer Rd", address_line2: "", city: "Devon", state: "PA", zip: "19333", primaryEC_fname: "Charles", primaryEC_lname: "Johnson", primaryEC_relationship: "Son", secondaryEC_fname: "", secondaryEC_lname: "", secondaryEC_relationship: "", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "P", phone: "(573) 268-2374", primaryEC_phone: "(723) 894-7239", secondaryEC_phone: "", tertiaryEC_phone: nil, cell: "(623) 984-7239", primaryEC_cell: "(723) 423-9847", secondaryEC_cell: "", tertiaryEC_cell: nil, full_name: "Betty P Johnson", confirmed: true},
  {fname: "Rita", lname: "Baker", email: "rita@baker.com", password_digest: "$2a$10$pArQ5to/dvhqJYQJvAD8JO7lQBf/oF.k2MLxRzFbL1uo80iWYOSse", address_line1: "601 Maplewood Ave", address_line2: "", city: "Wayne", state: "PA", zip: "19087", primaryEC_fname: "Tom", primaryEC_lname: "Baker", primaryEC_relationship: "Son", secondaryEC_fname: "", secondaryEC_lname: "", secondaryEC_relationship: "", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "R", phone: "(893) 278-4982", primaryEC_phone: "(789) 237-4239", secondaryEC_phone: "", tertiaryEC_phone: nil, cell: "(723) 472-3942", primaryEC_cell: "(238) 423-4792", secondaryEC_cell: "", tertiaryEC_cell: nil, full_name: "Rita R Baker", confirmed: true},
  {fname: "Marty", lname: "McFly", email: "marty@mcfly.com", password_digest: "$2a$10$xKSL4qpVglJVUeybuZPqiup/Qnumg.upottzu9wrZ3ZcWnca9iL7.", address_line1: "316 S Devon Ave", address_line2: "", city: "Devon", state: "PA", zip: "19087", primaryEC_fname: "Doc", primaryEC_lname: "Brown", primaryEC_relationship: "BFF", secondaryEC_fname: "", secondaryEC_lname: "", secondaryEC_relationship: "", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "M", phone: "(583) 298-2309", primaryEC_phone: "(238) 420-3948", secondaryEC_phone: "", tertiaryEC_phone: nil, cell: "(502) 938-4230", primaryEC_cell: "(876) 892-3748", secondaryEC_cell: "", tertiaryEC_cell: nil, full_name: "Marty M McFly", confirmed: true}
])
Origin.create!([
  {member_id: 1, address_line1: "416 St Davids Rd", address_line2: "", city: "Wayne", state: "PA", zip: "19087", primary: true, county: nil},
  {member_id: 2, address_line1: "100 Woods Ln", address_line2: "", city: "Wayne", state: "PA", zip: "19087", primary: true, county: nil},
  {member_id: 3, address_line1: "233 Highland Ave", address_line2: "", city: "Devon", state: "PA", zip: "19333", primary: true, county: nil},
  {member_id: 4, address_line1: "213 Spencer Rd", address_line2: "", city: "Devon", state: "PA", zip: "19333", primary: true, county: nil},
  {member_id: 5, address_line1: "601 Maplewood Ave", address_line2: "", city: "Wayne", state: "PA", zip: "19087", primary: true, county: nil},
  {member_id: 6, address_line1: "316 S Devon Ave", address_line2: "", city: "Devon", state: "PA", zip: "19087", primary: true, county: nil}
])
