Admin.create!([
  {fname: "Sample", lname: "Admin", username: nil, email: "admin@admin.com", password_digest: "password", super_admin: true, full_name: "Sample Admin", active: true}
])
Driver.create!([
  {fname: "Ricky", lname: "Bobby", email: "ricky@bobby.com", password_digest: "$2a$10$UapxqVCMQ/tILzPikZLV/OtmxW4/B16xmQ5Q4Ge/5zt4wKI3sGURy", address_line1: "1234 Real Fast Lane", address_line2: "", city: "Philadelphia", state: "PA", zip: "19120", car_type: "Four door", monday: true, tuesday: true, wednesday: true, thursday: true, friday: true, unavailable: nil, accommodate_wheelchair: true, accommodate_aide: true, preferred_contact: nil, phone: "(214) 142-3432", cell: "(234) 232-3523", monday_min: "2000-01-01 08:30:00", monday_max: "2000-01-01 16:30:00", tuesday_min: "2000-01-01 08:30:00", tuesday_max: "2000-01-01 16:30:00", wednesday_min: "2000-01-01 08:30:00", wednesday_max: "2000-01-01 16:30:00", thursday_min: "2000-01-01 08:30:00", thursday_max: "2000-01-01 16:30:00", friday_min: "2000-01-01 08:30:00", friday_max: "2000-01-01 16:30:00", county_preference: ["Chester County", "Delaware County", "Montgomery County", "Philadelphia County", "All"], full_name: "Ricky Bobby", private: nil, confirmed: true, active: true, prefered_contact: "Cell Phone", accommodate_pet: true},
  {fname: "Cal", lname: "Naughton Jr.", email: "cal@naughton.com", password_digest: "$2a$10$5yriX0QPGGkq8UaJghXsqOLrcoyeZ1EiYCAEpIK7bB.nCSqNPPVsO", address_line1: "4321 High Speed Rd", address_line2: "", city: "Talladega", state: "PA", zip: "19323", car_type: "Four door", monday: true, tuesday: false, wednesday: true, thursday: false, friday: true, unavailable: nil, accommodate_wheelchair: false, accommodate_aide: true, preferred_contact: nil, phone: "(231) 423-2234", cell: "(324) 235-3252", monday_min: "2000-01-01 08:30:00", monday_max: "2000-01-01 12:00:00", tuesday_min: nil, tuesday_max: nil, wednesday_min: "2000-01-01 08:30:00", wednesday_max: "2000-01-01 12:00:00", thursday_min: nil, thursday_max: nil, friday_min: "2000-01-01 08:30:00", friday_max: "2000-01-01 12:00:00", county_preference: ["Chester County", "Delaware County", "Montgomery County", "All"], full_name: "Cal Naughton Jr.", private: nil, confirmed: true, active: true, prefered_contact: "Cell Phone", accommodate_pet: true},
  {fname: "Jean", lname: "Girard", email: "jean@girard.com", password_digest: "$2a$10$T1Q5JSgW56HEpgoDj9G1RugbrJN0d40svNlOaRufAJbTgUUk6qNme", address_line1: "4312 Frenchman Rd", address_line2: "", city: "Paris", state: "PA", zip: "12312", car_type: "Two door", monday: true, tuesday: true, wednesday: true, thursday: true, friday: true, unavailable: nil, accommodate_wheelchair: true, accommodate_aide: false, preferred_contact: nil, phone: "(221) 212-3432", cell: "(324) 235-2343", monday_min: "2000-01-01 12:00:00", monday_max: "2000-01-01 16:30:00", tuesday_min: "2000-01-01 12:00:00", tuesday_max: "2000-01-01 16:30:00", wednesday_min: "2000-01-01 12:00:00", wednesday_max: "2000-01-01 16:30:00", thursday_min: "2000-01-01 12:00:00", thursday_max: "2000-01-01 16:30:00", friday_min: "2000-01-01 12:00:00", friday_max: "2000-01-01 16:30:00", county_preference: ["Chester County", "Delaware County", "All"], full_name: "Jean Girard", private: nil, confirmed: true, active: true, prefered_contact: "Cell Phone", accommodate_pet: true},
  {fname: "Reese", lname: "Bobby", email: "reese@bobby.com", password_digest: "$2a$10$MaENIQcLca5DE7ZTGX4CeehebrxG8QMYXK.naZu4N1SUsvZlzOhYG", address_line1: "333 Deadbeat Dad Boulevard ", address_line2: "", city: "Wayne", state: "PA", zip: "19323", car_type: "Four door", monday: true, tuesday: true, wednesday: true, thursday: true, friday: true, unavailable: nil, accommodate_wheelchair: true, accommodate_aide: true, preferred_contact: nil, phone: "(131) 232-1423", cell: "(212) 343-2342", monday_min: "2000-01-01 08:30:00", monday_max: "2000-01-01 16:30:00", tuesday_min: "2000-01-01 08:30:00", tuesday_max: "2000-01-01 13:00:00", wednesday_min: "2000-01-01 08:30:00", wednesday_max: "2000-01-01 14:15:00", thursday_min: "2000-01-01 08:30:00", thursday_max: "2000-01-01 13:45:00", friday_min: "2000-01-01 08:30:00", friday_max: "2000-01-01 14:15:00", county_preference: ["Chester County", "Montgomery County", "All"], full_name: "Reese Bobby", private: nil, confirmed: true, active: true, prefered_contact: "Cell Phone", accommodate_pet: false},
  {fname: "Speed", lname: "Racer", email: "speed@racer.com", password_digest: "$2a$10$kvcigIqwt5JNMTzPQeZkkeuP4HM9fXLRnT2VrNnaaw26BLB.HgUPK", address_line1: "15 Speed Way", address_line2: "", city: "Tokyo", state: "PA", zip: "34738", car_type: "Two door", monday: false, tuesday: false, wednesday: false, thursday: false, friday: true, unavailable: nil, accommodate_wheelchair: true, accommodate_aide: true, preferred_contact: nil, phone: "(823) 947-2394", cell: "(239) 048-2309", monday_min: nil, monday_max: nil, tuesday_min: nil, tuesday_max: nil, wednesday_min: nil, wednesday_max: nil, thursday_min: nil, thursday_max: nil, friday_min: "2000-01-01 08:30:00", friday_max: "2000-01-01 16:30:00", county_preference: ["Chester County", "Delaware County", "Montgomery County", "Philadelphia County", "All"], full_name: "Speed Racer", private: nil, confirmed: true, active: true, prefered_contact: "Cell Phone", accommodate_pet: true},
  {fname: "Jeff", lname: "Gordon", email: "jeff@gordon.com", password_digest: "$2a$10$FEuhk9MIQkEvQt2KAoa1eeK0imqiepi1iDYZSBIiu2UNtJjd2VvpS", address_line1: "532 NascarGuy street", address_line2: "", city: "Bumble", state: "PA", zip: "19234", car_type: "Four door", monday: true, tuesday: true, wednesday: true, thursday: true, friday: true, unavailable: nil, accommodate_wheelchair: true, accommodate_aide: true, preferred_contact: nil, phone: "(123) 124-2332", cell: "(324) 325-3453", monday_min: "2000-01-01 13:30:00", monday_max: "2000-01-01 16:30:00", tuesday_min: "2000-01-01 10:30:00", tuesday_max: "2000-01-01 16:00:00", wednesday_min: "2000-01-01 09:45:00", wednesday_max: "2000-01-01 16:15:00", thursday_min: "2000-01-01 10:15:00", thursday_max: "2000-01-01 16:00:00", friday_min: "2000-01-01 09:15:00", friday_max: "2000-01-01 15:45:00", county_preference: ["Chester County", "Delaware County", "Montgomery County", "All"], full_name: "Jeff Gordon", private: nil, confirmed: true, active: true, prefered_contact: "Cell Phone", accommodate_pet: false},
  {fname: "Mario", lname: "Andretti", email: "mario@andretti.com", password_digest: "$2a$10$OeE2xIi/ci/ZDG.Ighp0S.BsRdT3zuwRSTS9pejW.i1haysDBhRx6", address_line1: "902 Formula One Ave", address_line2: "", city: "Grand Prix", state: "PA", zip: "19322", car_type: "Four door", monday: true, tuesday: true, wednesday: false, thursday: true, friday: true, unavailable: nil, accommodate_wheelchair: true, accommodate_aide: true, preferred_contact: nil, phone: "(212) 242-1412", cell: "(116) 513-1235", monday_min: "2000-01-01 10:00:00", monday_max: "2000-01-01 15:00:00", tuesday_min: "2000-01-01 10:00:00", tuesday_max: "2000-01-01 15:00:00", wednesday_min: nil, wednesday_max: nil, thursday_min: "2000-01-01 10:00:00", thursday_max: "2000-01-01 15:00:00", friday_min: "2000-01-01 10:00:00", friday_max: "2000-01-01 15:00:00", county_preference: ["Chester County", "Delaware County", "Montgomery County", "Philadelphia County", "All"], full_name: "Mario Andretti", private: nil, confirmed: true, active: true, prefered_contact: "Home Phone", accommodate_pet: false},
  {fname: "Dale", lname: "Earnhardt", email: "dale@earnhardt", password_digest: "$2a$10$2ajW2OnXcKBZeHYa3F1e9uPNsdbClbjdql2er2ACyR5khR/4orhGe", address_line1: "5433 Nowhere Rd", address_line2: "", city: "Bumble", state: "PA", zip: "13243", car_type: "Two door", monday: true, tuesday: false, wednesday: false, thursday: true, friday: false, unavailable: nil, accommodate_wheelchair: true, accommodate_aide: true, preferred_contact: nil, phone: "(231) 343-2523", cell: "(324) 325-3452", monday_min: "2000-01-01 12:00:00", monday_max: "2000-01-01 16:30:00", tuesday_min: nil, tuesday_max: nil, wednesday_min: nil, wednesday_max: nil, thursday_min: "2000-01-01 09:00:00", thursday_max: "2000-01-01 15:45:00", friday_min: nil, friday_max: nil, county_preference: ["Chester County", "Delaware County", "Montgomery County", "All"], full_name: "Dale Earnhardt", private: nil, confirmed: true, active: true, prefered_contact: "Home Phone", accommodate_pet: true},
  {fname: "Dale", lname: "Earnhart Jr.", email: "dal@earnhardtjr.com", password_digest: "$2a$10$9dEeYAw5AT2opUI2E./NJuN2CSIzbM5MOb10PNmDmDtqOTxn9Nk0G", address_line1: "523 SonOfDale Ave", address_line2: "", city: "Racecar", state: "PA", zip: "21342", car_type: "Four door", monday: true, tuesday: true, wednesday: true, thursday: true, friday: true, unavailable: nil, accommodate_wheelchair: true, accommodate_aide: true, preferred_contact: nil, phone: "(234) 324-2352", cell: "(234) 235-3252", monday_min: "2000-01-01 10:45:00", monday_max: "2000-01-01 14:30:00", tuesday_min: "2000-01-01 10:45:00", tuesday_max: "2000-01-01 14:30:00", wednesday_min: "2000-01-01 10:45:00", wednesday_max: "2000-01-01 14:30:00", thursday_min: "2000-01-01 10:15:00", thursday_max: "2000-01-01 14:30:00", friday_min: "2000-01-01 10:45:00", friday_max: "2000-01-01 14:30:00", county_preference: ["Delaware County", "Montgomery County", "All"], full_name: "Dale Earnhart Jr.", private: nil, confirmed: true, active: true, prefered_contact: "Home Phone", accommodate_pet: false},
  {fname: "Michael", lname: "Schumacher", email: "michael@schumacher.com", password_digest: "$2a$10$yr/FvtovyWg9dY93.gCGDuUdQtnWLb8K0Q3zwJiE9apnH5CIxWitC", address_line1: "324 Round Street", address_line2: "", city: "Schumacher", state: "PA", zip: "19102", car_type: "Four door", monday: true, tuesday: false, wednesday: true, thursday: false, friday: true, unavailable: nil, accommodate_wheelchair: false, accommodate_aide: true, preferred_contact: nil, phone: "(213) 223-4523", cell: "(324) 325-2523", monday_min: "2000-01-01 08:30:00", monday_max: "2000-01-01 16:30:00", tuesday_min: nil, tuesday_max: nil, wednesday_min: "2000-01-01 08:30:00", wednesday_max: "2000-01-01 16:30:00", thursday_min: nil, thursday_max: nil, friday_min: "2000-01-01 08:30:00", friday_max: "2000-01-01 16:30:00", county_preference: ["Chester County", "Montgomery County", "All"], full_name: "Michael Schumacher", private: nil, confirmed: true, active: true, prefered_contact: "Email", accommodate_pet: true},
  {fname: "Dannica", lname: "Patrick", email: "dannica@patrick.com", password_digest: "$2a$10$AgboIv2F52sC/47J7JE7feei9stBb3J9fZccemW.n7OT49TByY/Hm", address_line1: "1234 Some Street", address_line2: "", city: "Wayne", state: "PA", zip: "19083", car_type: "Four door", monday: true, tuesday: true, wednesday: true, thursday: true, friday: false, unavailable: nil, accommodate_wheelchair: true, accommodate_aide: true, preferred_contact: nil, phone: "(545) 453-1351", cell: "(351) 513-5135", monday_min: "2000-01-01 08:30:00", monday_max: "2000-01-01 14:30:00", tuesday_min: "2000-01-01 08:30:00", tuesday_max: "2000-01-01 14:30:00", wednesday_min: "2000-01-01 08:30:00", wednesday_max: "2000-01-01 13:00:00", thursday_min: "2000-01-01 08:30:00", thursday_max: "2000-01-01 13:30:00", friday_min: nil, friday_max: nil, county_preference: ["Chester County", "Delaware County", "All"], full_name: "Dannica Patrick", private: nil, confirmed: true, active: true, prefered_contact: "Home Phone", accommodate_pet: false},
  {fname: "Richard", lname: "Petty", email: "richard@petty.com", password_digest: "$2a$10$i9K.W8yyom8uSJ5I5Gh6quIHJ8FBbkx79S6yK5UHkM.aAQApdn2Be", address_line1: "508 Nascar Road", address_line2: "", city: "Devon", state: "PA", zip: "19083", car_type: "Four door", monday: true, tuesday: true, wednesday: true, thursday: true, friday: true, unavailable: nil, accommodate_wheelchair: true, accommodate_aide: true, preferred_contact: nil, phone: "(542) 555-4242", cell: "(351) 351-5324", monday_min: "2000-01-01 12:00:00", monday_max: "2000-01-01 16:30:00", tuesday_min: "2000-01-01 12:00:00", tuesday_max: "2000-01-01 16:30:00", wednesday_min: "2000-01-01 12:00:00", wednesday_max: "2000-01-01 16:30:00", thursday_min: "2000-01-01 12:00:00", thursday_max: "2000-01-01 16:30:00", friday_min: "2000-01-01 12:00:00", friday_max: "2000-01-01 16:30:00", county_preference: ["Chester County", "Montgomery County", "All"], full_name: "Richard Petty", private: nil, confirmed: true, active: true, prefered_contact: "Home Phone", accommodate_pet: true},
  {fname: "Jimmi", lname: "Johnson", email: "jimmie@johnson.com", password_digest: "$2a$10$pXs46xQ2It3tnbrCcQfloO02gtAqxIBA/af2.gU0wl/aE3XZ110Du", address_line1: "123 Real Fast Lane", address_line2: "", city: "Oaks", state: "PA", zip: "19432", car_type: "Four door", monday: true, tuesday: true, wednesday: true, thursday: true, friday: true, unavailable: nil, accommodate_wheelchair: false, accommodate_aide: true, preferred_contact: nil, phone: "(213) 214-3322", cell: "(142) 342-3324", monday_min: "2000-01-01 09:15:00", monday_max: "2000-01-01 15:00:00", tuesday_min: "2000-01-01 09:15:00", tuesday_max: "2000-01-01 15:00:00", wednesday_min: "2000-01-01 09:00:00", wednesday_max: "2000-01-01 15:00:00", thursday_min: "2000-01-01 09:00:00", thursday_max: "2000-01-01 15:00:00", friday_min: "2000-01-01 09:00:00", friday_max: "2000-01-01 15:00:00", county_preference: ["Delaware County", "Montgomery County", "All"], full_name: "Jimmi Johnson", private: nil, confirmed: true, active: true, prefered_contact: "Home Phone", accommodate_pet: false}
])
Destination.create!([
  {member_id: 1, name: "Mike Robinson", address_line1: "510 Spring Mill Ave", address_line2: "", city: "Conshohocken", state: "PA", zip: "19428", destination_type: "grocery", destination_other_type: nil, county: "Montgomery County"},
  {member_id: 6, name: "The Future (Whole Foods)", address_line1: "821 Lancaster Avenue", address_line2: "", city: "Wayne", state: "PA", zip: "19087", destination_type: "grocery", destination_other_type: nil, county: "All"},
  {member_id: 7, name: "ACME", address_line1: "700 West Lancaster Avenue", address_line2: "", city: "Devon", state: "PA", zip: "19087", destination_type: "grocery", destination_other_type: nil, county: "All"},
  {member_id: 9, name: "CVS", address_line1: "316 W Lancaster Ave", address_line2: "", city: "Wayne", state: "PA", zip: "19087", destination_type: "doctor", destination_other_type: nil, county: "Delaware County"},
  {member_id: 10, name: "Rite Aid", address_line1: "644 West Lancaster Ave", address_line2: "", city: "Wayne", state: "PA", zip: "19087", destination_type: "doctor", destination_other_type: nil, county: "Delaware County"},
  {member_id: 2, name: "Devon Family Practice", address_line1: "139 Berkeley Rd", address_line2: "", city: "Devon", state: "PA", zip: "19333", destination_type: "doctor", destination_other_type: nil, county: "Chester County"},
  {member_id: 5, name: "Posh Hair Studio", address_line1: "886 W Lancaster Ave", address_line2: "", city: "Devon", state: "PA", zip: "19333", destination_type: "salon", destination_other_type: nil, county: "All"},
  {member_id: 4, name: "Prestige Salon", address_line1: "841 W Lancaster Ave", address_line2: "", city: "Wayne", state: "PA", zip: "19087", destination_type: "salon", destination_other_type: nil, county: "Delaware County"},
  {member_id: 2, name: "CVS", address_line1: "550 W Lancaster Ave", address_line2: "", city: "Berwyn", state: "PA", zip: "19132", destination_type: nil, destination_other_type: nil, county: "All"},
  {member_id: 3, name: "Mimi's Berwyn Hair Designs", address_line1: "4 Midland Ave # 102", address_line2: "", city: "Berwyn", state: "PA", zip: "19312", destination_type: "salon", destination_other_type: nil, county: "All"},
  {member_id: 8, name: "Devon Nails & Spa", address_line1: "845 W Lancaster Ave", address_line2: "", city: "Devon", state: "PA", zip: "19333", destination_type: "salon", destination_other_type: nil, county: "All"},
  {member_id: 1, name: "Devon Lanes", address_line1: "300 West Lancaster Avenue", address_line2: "", city: "Devon", state: "PA", zip: "19333", destination_type: nil, destination_other_type: nil, county: "All"},
  {member_id: 2, name: "Whole Foods", address_line1: "821 Lancaster Avenue", address_line2: "", city: "Wayne", state: "PA", zip: "19087", destination_type: "grocery", destination_other_type: nil, county: "All"},
  {member_id: 2, name: "ACME", address_line1: "700 West Lancaster Avenue", address_line2: "", city: "Devon", state: "PA", zip: "19087", destination_type: "grocery", destination_other_type: nil, county: "All"},
  {member_id: 9, name: "ACME", address_line1: "700 West Lancaster Avenue", address_line2: "", city: "Devon", state: "PA", zip: "19087", destination_type: "grocery", destination_other_type: nil, county: "All"},
  {member_id: 5, name: "ACME", address_line1: "700 West Lancaster Avenue", address_line2: "", city: "Wayne", state: "PA", zip: "19087", destination_type: "grocery", destination_other_type: nil, county: "Delaware County"},
  {member_id: 8, name: "ACME", address_line1: "700 West Lancaster Avenue", address_line2: "", city: "Wayne", state: "PA", zip: "19087", destination_type: "grocery", destination_other_type: nil, county: "Delaware County"},
  {member_id: 6, name: "ACME", address_line1: "700 West Lancaster Avenue", address_line2: "", city: "Wayne", state: "PA", zip: "19087", destination_type: "grocery", destination_other_type: nil, county: "Delaware County"}
])
Match.create!([
  {ride_id: 1, matcher_id: 1},
  {ride_id: 2, matcher_id: 1},
  {ride_id: 2, matcher_id: 4},
  {ride_id: 2, matcher_id: 5},
  {ride_id: 2, matcher_id: 6},
  {ride_id: 2, matcher_id: 8},
  {ride_id: 2, matcher_id: 10},
  {ride_id: 2, matcher_id: 11},
  {ride_id: 2, matcher_id: 12},
  {ride_id: 3, matcher_id: 1},
  {ride_id: 4, matcher_id: 1},
  {ride_id: 4, matcher_id: 3},
  {ride_id: 4, matcher_id: 5},
  {ride_id: 5, matcher_id: 1},
  {ride_id: 5, matcher_id: 3},
  {ride_id: 5, matcher_id: 4},
  {ride_id: 5, matcher_id: 5},
  {ride_id: 5, matcher_id: 10},
  {ride_id: 5, matcher_id: 6},
  {ride_id: 5, matcher_id: 8},
  {ride_id: 5, matcher_id: 9},
  {ride_id: 6, matcher_id: 1},
  {ride_id: 6, matcher_id: 3},
  {ride_id: 6, matcher_id: 6},
  {ride_id: 6, matcher_id: 9},
  {ride_id: 8, matcher_id: 1},
  {ride_id: 8, matcher_id: 4},
  {ride_id: 8, matcher_id: 5},
  {ride_id: 8, matcher_id: 10},
  {ride_id: 8, matcher_id: 7},
  {ride_id: 8, matcher_id: 8},
  {ride_id: 8, matcher_id: 12},
  {ride_id: 9, matcher_id: 1},
  {ride_id: 9, matcher_id: 5},
  {ride_id: 9, matcher_id: 11},
  {ride_id: 9, matcher_id: 9},
  {ride_id: 10, matcher_id: 1},
  {ride_id: 10, matcher_id: 2},
  {ride_id: 10, matcher_id: 11},
  {ride_id: 11, matcher_id: 1},
  {ride_id: 11, matcher_id: 3},
  {ride_id: 11, matcher_id: 5},
  {ride_id: 11, matcher_id: 10},
  {ride_id: 11, matcher_id: 7},
  {ride_id: 11, matcher_id: 8},
  {ride_id: 11, matcher_id: 9},
  {ride_id: 12, matcher_id: 1},
  {ride_id: 12, matcher_id: 3},
  {ride_id: 12, matcher_id: 4},
  {ride_id: 12, matcher_id: 5},
  {ride_id: 12, matcher_id: 10},
  {ride_id: 12, matcher_id: 6},
  {ride_id: 12, matcher_id: 7},
  {ride_id: 12, matcher_id: 11},
  {ride_id: 12, matcher_id: 8},
  {ride_id: 12, matcher_id: 9},
  {ride_id: 12, matcher_id: 12},
  {ride_id: 13, matcher_id: 1},
  {ride_id: 13, matcher_id: 3},
  {ride_id: 13, matcher_id: 5},
  {ride_id: 13, matcher_id: 10},
  {ride_id: 13, matcher_id: 9},
  {ride_id: 13, matcher_id: 12},
  {ride_id: 14, matcher_id: 1},
  {ride_id: 14, matcher_id: 3},
  {ride_id: 14, matcher_id: 4},
  {ride_id: 14, matcher_id: 5},
  {ride_id: 14, matcher_id: 10},
  {ride_id: 14, matcher_id: 6},
  {ride_id: 14, matcher_id: 7},
  {ride_id: 14, matcher_id: 8},
  {ride_id: 14, matcher_id: 9},
  {ride_id: 14, matcher_id: 12},
  {ride_id: 15, matcher_id: 1},
  {ride_id: 15, matcher_id: 4},
  {ride_id: 15, matcher_id: 8},
  {ride_id: 15, matcher_id: 12},
  {ride_id: 16, matcher_id: 1},
  {ride_id: 16, matcher_id: 3},
  {ride_id: 16, matcher_id: 4},
  {ride_id: 16, matcher_id: 5},
  {ride_id: 16, matcher_id: 7},
  {ride_id: 16, matcher_id: 11},
  {ride_id: 16, matcher_id: 8},
  {ride_id: 16, matcher_id: 9},
  {ride_id: 16, matcher_id: 12},
  {ride_id: 17, matcher_id: 1},
  {ride_id: 17, matcher_id: 5},
  {ride_id: 17, matcher_id: 10},
  {ride_id: 17, matcher_id: 6},
  {ride_id: 17, matcher_id: 7},
  {ride_id: 17, matcher_id: 8},
  {ride_id: 17, matcher_id: 12},
  {ride_id: 18, matcher_id: 1},
  {ride_id: 18, matcher_id: 2},
  {ride_id: 18, matcher_id: 4},
  {ride_id: 18, matcher_id: 10},
  {ride_id: 18, matcher_id: 7},
  {ride_id: 18, matcher_id: 11},
  {ride_id: 18, matcher_id: 8},
  {ride_id: 18, matcher_id: 12},
  {ride_id: 19, matcher_id: 1},
  {ride_id: 19, matcher_id: 3},
  {ride_id: 19, matcher_id: 5},
  {ride_id: 19, matcher_id: 11},
  {ride_id: 19, matcher_id: 9},
  {ride_id: 20, matcher_id: 1},
  {ride_id: 20, matcher_id: 3},
  {ride_id: 20, matcher_id: 5},
  {ride_id: 20, matcher_id: 7},
  {ride_id: 20, matcher_id: 12},
  {ride_id: 21, matcher_id: 1},
  {ride_id: 21, matcher_id: 2},
  {ride_id: 21, matcher_id: 4},
  {ride_id: 21, matcher_id: 5},
  {ride_id: 21, matcher_id: 7},
  {ride_id: 21, matcher_id: 11},
  {ride_id: 21, matcher_id: 8},
  {ride_id: 21, matcher_id: 12},
  {ride_id: 22, matcher_id: 1},
  {ride_id: 22, matcher_id: 3},
  {ride_id: 22, matcher_id: 5},
  {ride_id: 22, matcher_id: 10},
  {ride_id: 22, matcher_id: 7},
  {ride_id: 22, matcher_id: 8},
  {ride_id: 22, matcher_id: 9},
  {ride_id: 22, matcher_id: 12},
  {ride_id: 23, matcher_id: 1},
  {ride_id: 23, matcher_id: 2},
  {ride_id: 23, matcher_id: 3},
  {ride_id: 23, matcher_id: 10},
  {ride_id: 23, matcher_id: 6},
  {ride_id: 23, matcher_id: 7},
  {ride_id: 23, matcher_id: 8},
  {ride_id: 23, matcher_id: 12},
  {ride_id: 24, matcher_id: 1},
  {ride_id: 24, matcher_id: 2},
  {ride_id: 24, matcher_id: 4},
  {ride_id: 24, matcher_id: 11},
  {ride_id: 24, matcher_id: 8},
  {ride_id: 24, matcher_id: 12},
  {ride_id: 26, matcher_id: 1},
  {ride_id: 26, matcher_id: 3},
  {ride_id: 26, matcher_id: 4},
  {ride_id: 26, matcher_id: 5},
  {ride_id: 26, matcher_id: 10},
  {ride_id: 26, matcher_id: 6},
  {ride_id: 26, matcher_id: 7},
  {ride_id: 26, matcher_id: 11},
  {ride_id: 26, matcher_id: 8},
  {ride_id: 26, matcher_id: 9},
  {ride_id: 26, matcher_id: 12},
  {ride_id: 27, matcher_id: 1},
  {ride_id: 27, matcher_id: 3},
  {ride_id: 27, matcher_id: 5},
  {ride_id: 27, matcher_id: 10},
  {ride_id: 27, matcher_id: 7},
  {ride_id: 27, matcher_id: 8},
  {ride_id: 27, matcher_id: 12},
  {ride_id: 28, matcher_id: 1},
  {ride_id: 28, matcher_id: 5},
  {ride_id: 28, matcher_id: 11},
  {ride_id: 28, matcher_id: 9},
  {ride_id: 29, matcher_id: 1},
  {ride_id: 29, matcher_id: 5},
  {ride_id: 29, matcher_id: 10},
  {ride_id: 29, matcher_id: 6},
  {ride_id: 29, matcher_id: 7},
  {ride_id: 29, matcher_id: 8},
  {ride_id: 29, matcher_id: 12},
  {ride_id: 30, matcher_id: 1},
  {ride_id: 30, matcher_id: 3},
  {ride_id: 30, matcher_id: 5},
  {ride_id: 30, matcher_id: 7},
  {ride_id: 30, matcher_id: 12}
])
Matcher.create!([
  {driver_id: 1, match_num: nil},
  {driver_id: 2, match_num: nil},
  {driver_id: 3, match_num: nil},
  {driver_id: 4, match_num: nil},
  {driver_id: 5, match_num: nil},
  {driver_id: 6, match_num: nil},
  {driver_id: 7, match_num: nil},
  {driver_id: 8, match_num: nil},
  {driver_id: 9, match_num: nil},
  {driver_id: 10, match_num: nil},
  {driver_id: 11, match_num: nil},
  {driver_id: 12, match_num: nil},
  {driver_id: 13, match_num: nil}
])
Member.create!([
  {fname: "George", lname: "Williams", email: "george@williams.com", password_digest: "$2a$10$D0zvp/5kCfOy9N8AnURs.Ov/yj0c5Vnl984dSFlq2lPLWj/h9eWsm", address_line1: "100 Woods Ln", address_line2: "", city: "Wayne", state: "PA", zip: "19087", primaryEC_fname: "Jeff", primaryEC_lname: "Williams", primaryEC_relationship: "Son", secondaryEC_fname: "", secondaryEC_lname: "", secondaryEC_relationship: "", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "Q", phone: "(234) 723-4872", primaryEC_phone: "(238) 472-9384", secondaryEC_phone: "", tertiaryEC_phone: nil, cell: "(922) 342-3434", primaryEC_cell: "(234) 234-2342", secondaryEC_cell: "", tertiaryEC_cell: nil, full_name: "George Q Williams", confirmed: true},
  {fname: "John", lname: "Smith", email: "john@smith.com", password_digest: "$2a$10$3uKDVqhIj5Q86SObreTj3OkT/kYI4ON5vnRN7asPcy5t1OhJeljcW", address_line1: "416 St Davids Rd", address_line2: "", city: "Wayne", state: "PA", zip: "19087", primaryEC_fname: "Jane", primaryEC_lname: "Smith", primaryEC_relationship: "Spouse", secondaryEC_fname: "", secondaryEC_lname: "", secondaryEC_relationship: "", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "D", phone: "(723) 984-7329", primaryEC_phone: "(239) 847-2394", secondaryEC_phone: "", tertiaryEC_phone: nil, cell: "(623) 498-1303", primaryEC_cell: "(897) 982-3723", secondaryEC_cell: "", tertiaryEC_cell: nil, full_name: "John D Smith", confirmed: true},
  {fname: "Paul", lname: "Jones", email: "paul@jones.com", password_digest: "$2a$10$oz43KwRSLOy3Qq46rYEB2er2Ww8gvw1Dv5WXBaM/1NP5B37vb2FKO", address_line1: "233 Highland Ave", address_line2: "", city: "Devon", state: "PA", zip: "19333", primaryEC_fname: "Rose", primaryEC_lname: "Jones", primaryEC_relationship: "Daughter", secondaryEC_fname: "", secondaryEC_lname: "", secondaryEC_relationship: "", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "F", phone: "(897) 239-8792", primaryEC_phone: "(238) 979-8237", secondaryEC_phone: "", tertiaryEC_phone: nil, cell: "(234) 782-3642", primaryEC_cell: "(923) 847-2394", secondaryEC_cell: "", tertiaryEC_cell: nil, full_name: "Paul F Jones", confirmed: true},
  {fname: "Betty", lname: "Johnson", email: "betty@johnson.com", password_digest: "$2a$10$jRDMbC5NXFNniX740QxLJurdB.ySFLzg4KsyFYG4qtqi8WDYRt3am", address_line1: "213 Spencer Rd", address_line2: "", city: "Devon", state: "PA", zip: "19333", primaryEC_fname: "Charles", primaryEC_lname: "Johnson", primaryEC_relationship: "Son", secondaryEC_fname: "", secondaryEC_lname: "", secondaryEC_relationship: "", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "P", phone: "(573) 268-2374", primaryEC_phone: "(723) 894-7239", secondaryEC_phone: "", tertiaryEC_phone: nil, cell: "(623) 984-7239", primaryEC_cell: "(723) 423-9847", secondaryEC_cell: "", tertiaryEC_cell: nil, full_name: "Betty P Johnson", confirmed: true},
  {fname: "Rita", lname: "Baker", email: "rita@baker.com", password_digest: "$2a$10$pArQ5to/dvhqJYQJvAD8JO7lQBf/oF.k2MLxRzFbL1uo80iWYOSse", address_line1: "601 Maplewood Ave", address_line2: "", city: "Wayne", state: "PA", zip: "19087", primaryEC_fname: "Tom", primaryEC_lname: "Baker", primaryEC_relationship: "Son", secondaryEC_fname: "", secondaryEC_lname: "", secondaryEC_relationship: "", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "R", phone: "(893) 278-4982", primaryEC_phone: "(789) 237-4239", secondaryEC_phone: "", tertiaryEC_phone: nil, cell: "(723) 472-3942", primaryEC_cell: "(238) 423-4792", secondaryEC_cell: "", tertiaryEC_cell: nil, full_name: "Rita R Baker", confirmed: true},
  {fname: "Marty", lname: "McFly", email: "marty@mcfly.com", password_digest: "$2a$10$xKSL4qpVglJVUeybuZPqiup/Qnumg.upottzu9wrZ3ZcWnca9iL7.", address_line1: "316 S Devon Ave", address_line2: "", city: "Devon", state: "PA", zip: "19087", primaryEC_fname: "Doc", primaryEC_lname: "Brown", primaryEC_relationship: "BFF", secondaryEC_fname: "", secondaryEC_lname: "", secondaryEC_relationship: "", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "M", phone: "(583) 298-2309", primaryEC_phone: "(238) 420-3948", secondaryEC_phone: "", tertiaryEC_phone: nil, cell: "(502) 938-4230", primaryEC_cell: "(876) 892-3748", secondaryEC_cell: "", tertiaryEC_cell: nil, full_name: "Marty M McFly", confirmed: true},
  {fname: "Barney", lname: "Rubble", email: "barney@rubble.com", password_digest: "$2a$10$sto7f8czQ1Nr0n9PNPayhuCE9/nscHjkIXeOICVHBpVlNMIdI2Dc2", address_line1: "407 Portland Dr", address_line2: "", city: "Broomall", state: "PA", zip: "19008", primaryEC_fname: "Betty", primaryEC_lname: "Rubble", primaryEC_relationship: "Spouse", secondaryEC_fname: "", secondaryEC_lname: "", secondaryEC_relationship: "", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "B", phone: "(233) 280-9234", primaryEC_phone: "(837) 230-9482", secondaryEC_phone: "", tertiaryEC_phone: nil, cell: "(789) 237-9234", primaryEC_cell: "(092) 380-9238", secondaryEC_cell: "", tertiaryEC_cell: nil, full_name: "Barney B Rubble", confirmed: true},
  {fname: "Marge", lname: "Simpson", email: "marge@simpson.com", password_digest: "$2a$10$3uAAKp98lko63913zrFQHeMS7YGg/v.RjowX.o97oseugxaYRbRs6", address_line1: "336 Pinecrest Rd", address_line2: "", city: "Springfield", state: "PA", zip: "19064", primaryEC_fname: "Lisa", primaryEC_lname: "Simpson", primaryEC_relationship: "daughter", secondaryEC_fname: "", secondaryEC_lname: "", secondaryEC_relationship: "", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "Q", phone: "(492) 380-9238", primaryEC_phone: "(893) 472-3947", secondaryEC_phone: "", tertiaryEC_phone: nil, cell: "(902) 380-9234", primaryEC_cell: "(289) 374-2398", secondaryEC_cell: "", tertiaryEC_cell: nil, full_name: "Marge Q Simpson", confirmed: true},
  {fname: "Hubert", lname: "Farnsworth", email: "hubert@farnsworth.com", password_digest: "$2a$10$1vWzsBneZb6iiR.g/BIYC./jG5QbRuOt3d5iyQFyxJgmbCzaaNzWq", address_line1: "532 Harrington Rd", address_line2: "", city: "Havertown", state: "PA", zip: "19083", primaryEC_fname: "Philip", primaryEC_lname: "Fry", primaryEC_relationship: "Uncle", secondaryEC_fname: "", secondaryEC_lname: "", secondaryEC_relationship: "", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "J", phone: "(298) 374-3928", primaryEC_phone: "(093) 823-0948", secondaryEC_phone: "", tertiaryEC_phone: nil, cell: "(239) 084-2093", primaryEC_cell: "(092) 384-0923", secondaryEC_cell: "", tertiaryEC_cell: nil, full_name: "Hubert J Farnsworth", confirmed: true},
  {fname: "Marie", lname: "Barone", email: "marie@barone.com", password_digest: "$2a$10$w2qw1iFpG65A1RnEiPQZCeSLGPVpxVjdGcFbIiQS3M2iXjLXmBVLu", address_line1: "118 Hillside Rd", address_line2: "", city: "Wayne", state: "PA", zip: "19087", primaryEC_fname: "Raymond", primaryEC_lname: "Barone", primaryEC_relationship: "Son", secondaryEC_fname: "Robert", secondaryEC_lname: "Barone", secondaryEC_relationship: "Son", tertiaryEC_fname: nil, tertiaryEC_lname: nil, tertiaryEC_local_exchange: nil, tertiaryEC_relationship: nil, active: true, mi: "J", phone: "(749) 834-7329", primaryEC_phone: "(389) 423-9048", secondaryEC_phone: "(823) 749-8234", tertiaryEC_phone: nil, cell: "(738) 492-3749", primaryEC_cell: "(092) 384-0923", secondaryEC_cell: "(982) 390-4823", tertiaryEC_cell: nil, full_name: "Marie J Barone", confirmed: true}
])
Note.create!([
  {admin_id: 1, driver_id: nil, ride_id: 5, body: "John recently had surgery and will require assistance at the appointment"},
  {admin_id: 1, driver_id: nil, ride_id: 7, body: "Ride outside of normal schedule range. Will try to find someone willing to drive."},
  {admin_id: 1, driver_id: nil, ride_id: 25, body: "This ride falls outside of the range of normal driver's schedules, so no matches.  "},
  {admin_id: 1, driver_id: nil, ride_id: 2, body: "Pick up Barney Rubble and his cat."}
])
Origin.create!([
  {member_id: 1, address_line1: "416 St Davids Rd", address_line2: "", city: "Wayne", state: "PA", zip: "19087", primary: true, county: nil},
  {member_id: 2, address_line1: "100 Woods Ln", address_line2: "", city: "Wayne", state: "PA", zip: "19087", primary: true, county: nil},
  {member_id: 3, address_line1: "233 Highland Ave", address_line2: "", city: "Devon", state: "PA", zip: "19333", primary: true, county: nil},
  {member_id: 4, address_line1: "213 Spencer Rd", address_line2: "", city: "Devon", state: "PA", zip: "19333", primary: true, county: nil},
  {member_id: 5, address_line1: "601 Maplewood Ave", address_line2: "", city: "Wayne", state: "PA", zip: "19087", primary: true, county: nil},
  {member_id: 6, address_line1: "316 S Devon Ave", address_line2: "", city: "Devon", state: "PA", zip: "19087", primary: true, county: nil},
  {member_id: 7, address_line1: "407 Portland Dr", address_line2: "", city: "Broomall", state: "PA", zip: "19008", primary: true, county: nil},
  {member_id: 8, address_line1: "336 Pinecrest Rd", address_line2: "", city: "Springfield", state: "PA", zip: "19064", primary: true, county: nil},
  {member_id: 9, address_line1: "532 Harrington Rd", address_line2: "", city: "Havertown", state: "PA", zip: "19083", primary: true, county: nil},
  {member_id: 10, address_line1: "118 Hillside Rd", address_line2: "", city: "Wayne", state: "PA", zip: "19087", primary: true, county: nil}
])
Outreach.create!([
  {driver_id: 10, ride_id: 5, contact_method: "cell", result: "left message", admin_id: 1},
  {driver_id: 7, ride_id: 5, contact_method: "email", result: "left message", admin_id: 1},
  {driver_id: 1, ride_id: 7, contact_method: "cell", result: "waiting to hear back", admin_id: 1},
  {driver_id: 10, ride_id: 8, contact_method: "cell", result: "driver declined", admin_id: 1},
  {driver_id: 1, ride_id: 8, contact_method: "cell", result: "driver assigned", admin_id: 1},
  {driver_id: 7, ride_id: 11, contact_method: "cell", result: "driver assigned", admin_id: 1},
  {driver_id: 5, ride_id: 4, contact_method: "cell", result: "left message", admin_id: 1},
  {driver_id: 5, ride_id: 4, contact_method: "cell", result: "left message", admin_id: 1},
  {driver_id: 10, ride_id: 13, contact_method: "cell", result: "driver declined", admin_id: 1},
  {driver_id: 1, ride_id: 13, contact_method: "cell", result: "driver declined", admin_id: 1},
  {driver_id: 3, ride_id: 13, contact_method: "cell", result: "driver declined", admin_id: 1},
  {driver_id: 10, ride_id: 14, contact_method: "cell", result: "left message", admin_id: 1},
  {driver_id: 1, ride_id: 15, contact_method: "cell", result: "driver declined", admin_id: 1},
  {driver_id: 4, ride_id: 15, contact_method: "cell", result: "driver declined", admin_id: 1},
  {driver_id: 10, ride_id: 18, contact_method: "cell", result: "left message", admin_id: 1},
  {driver_id: 1, ride_id: 19, contact_method: "cell", result: "driver declined", admin_id: 1},
  {driver_id: 10, ride_id: 23, contact_method: "cell", result: "waiting to hear back", admin_id: 1},
  {driver_id: 10, ride_id: 26, contact_method: "cell", result: "driver declined", admin_id: 1},
  {driver_id: 4, ride_id: 26, contact_method: "email", result: "left message", admin_id: 1},
  {driver_id: 10, ride_id: 27, contact_method: "cell", result: "driver declined", admin_id: 1},
  {driver_id: 12, ride_id: 2, contact_method: "email", result: "left message", admin_id: 1},
  {driver_id: 1, ride_id: 10, contact_method: "email", result: "left message", admin_id: 1},
  {driver_id: 10, ride_id: 29, contact_method: "cell", result: "left message", admin_id: 1},
  {driver_id: 5, ride_id: 29, contact_method: "cell", result: "driver assigned", admin_id: 1},
  {driver_id: 1, ride_id: 30, contact_method: "cell", result: "driver assigned", admin_id: 1}
])
Ride.create!([
  {member_id: 4, driver_id: 1, origin_id: 4, destination_id: 8, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "scheduled", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/13", pickup_time: "2000-01-01 14:00:00", assigned_by: "Sample Admin", duration: "1.5 hours", pet: false},
  {member_id: 2, driver_id: nil, origin_id: 2, destination_id: 6, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: true, recurring: nil, status: "open", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/28", pickup_time: "2000-01-01 13:30:00", assigned_by: nil, duration: "1 hour", pet: false},
  {member_id: 5, driver_id: nil, origin_id: 5, destination_id: 7, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: true, recurring: nil, status: "open", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/21", pickup_time: "2000-01-01 12:30:00", assigned_by: nil, duration: "1 hour", pet: true},
  {member_id: 4, driver_id: nil, origin_id: 4, destination_id: 8, wheelchair: true, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "open", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/29", pickup_time: "2000-01-01 19:00:00", assigned_by: nil, duration: "2.5 hours", pet: false},
  {member_id: 2, driver_id: 1, origin_id: 2, destination_id: 9, wheelchair: false, aide: true, vision_impaired: false, hearing_impaired: true, recurring: nil, status: "scheduled", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/19", pickup_time: "2000-01-01 11:00:00", assigned_by: "Sample Admin", duration: "1 hour", pet: false},
  {member_id: 8, driver_id: nil, origin_id: 8, destination_id: 11, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "open", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/20", pickup_time: "2000-01-01 09:30:00", assigned_by: nil, duration: "1 hour", pet: true},
  {member_id: 2, driver_id: nil, origin_id: 2, destination_id: 13, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: true, recurring: nil, status: "canceled", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/18", pickup_time: "2000-01-01 13:30:00", assigned_by: nil, duration: "2 hours", pet: false},
  {member_id: 1, driver_id: 7, origin_id: 1, destination_id: 12, wheelchair: true, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "scheduled", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/19", pickup_time: "2000-01-01 14:15:00", assigned_by: "Sample Admin", duration: "1.5 hours", pet: false},
  {member_id: 3, driver_id: nil, origin_id: 3, destination_id: 10, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "open", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/02/23", pickup_time: "2000-01-01 15:00:00", assigned_by: nil, duration: "2 hours", pet: false},
  {member_id: 10, driver_id: 5, origin_id: 10, destination_id: 5, wheelchair: true, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "scheduled", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/20", pickup_time: "2000-01-01 15:45:00", assigned_by: "Sample Admin", duration: "1 hour", pet: false},
  {member_id: 3, driver_id: 9, origin_id: 3, destination_id: 10, wheelchair: false, aide: true, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "scheduled", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/20", pickup_time: "2000-01-01 15:45:00", assigned_by: "Sample Admin", duration: "2.5 hours", pet: false},
  {member_id: 9, driver_id: 1, origin_id: 9, destination_id: 4, wheelchair: true, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "scheduled", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/25", pickup_time: "2000-01-01 09:30:00", assigned_by: "Sample Admin", duration: "1 hour", pet: true},
  {member_id: 7, driver_id: nil, origin_id: 7, destination_id: 3, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: true, recurring: nil, status: "open", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/28", pickup_time: "2000-01-01 12:30:00", assigned_by: nil, duration: "2 hours", pet: false},
  {member_id: 2, driver_id: 1, origin_id: 2, destination_id: 14, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "canceled", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/06", pickup_time: "2000-01-01 13:00:00", assigned_by: "Sample Admin", duration: "1.5 hours", pet: false},
  {member_id: 4, driver_id: nil, origin_id: 4, destination_id: 8, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "canceled", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2015/12/24", pickup_time: "2000-01-01 11:30:00", assigned_by: nil, duration: "2 hours", pet: false},
  {member_id: 1, driver_id: nil, origin_id: 1, destination_id: 12, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "open", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/02/24", pickup_time: "2000-01-01 15:30:00", assigned_by: nil, duration: "2.5 hours", pet: false},
  {member_id: 1, driver_id: 2, origin_id: 1, destination_id: 12, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "complete", completion_notes: "George complained of headaches to the driver during the ride", requested_driver: nil, request_checked: nil, pickup_date: "2015/11/18", pickup_time: "2000-01-01 11:30:00", assigned_by: "Sample Admin", duration: "3 hours", pet: false},
  {member_id: 4, driver_id: 3, origin_id: 4, destination_id: 8, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "complete", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2015/12/16", pickup_time: "2000-01-01 14:30:00", assigned_by: "Sample Admin", duration: "3 hours", pet: false},
  {member_id: 8, driver_id: 9, origin_id: 8, destination_id: 11, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "complete", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2015/12/22", pickup_time: "2000-01-01 14:30:00", assigned_by: "Sample Admin", duration: "1.5 hours", pet: false},
  {member_id: 6, driver_id: 1, origin_id: 6, destination_id: 2, wheelchair: false, aide: false, vision_impaired: true, hearing_impaired: false, recurring: nil, status: "complete", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/07", pickup_time: "2000-01-01 10:00:00", assigned_by: "Sample Admin", duration: "1.5 hours", pet: false},
  {member_id: 8, driver_id: 5, origin_id: 8, destination_id: 17, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "scheduled", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/12", pickup_time: "2000-01-01 13:00:00", assigned_by: "Sample Admin", duration: "2 hours", pet: false},
  {member_id: 2, driver_id: nil, origin_id: 2, destination_id: 6, wheelchair: false, aide: true, vision_impaired: true, hearing_impaired: false, recurring: nil, status: "open", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/20", pickup_time: "2000-01-01 15:30:00", assigned_by: nil, duration: "1 hour", pet: false},
  {member_id: 7, driver_id: 4, origin_id: 7, destination_id: 3, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "scheduled", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/21", pickup_time: "2000-01-01 10:30:00", assigned_by: "Sample Admin", duration: "1 hour", pet: false},
  {member_id: 2, driver_id: 12, origin_id: 2, destination_id: 14, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "scheduled", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/02/02", pickup_time: "2000-01-01 09:30:00", assigned_by: "Sample Admin", duration: "2 hours", pet: false},
  {member_id: 9, driver_id: 12, origin_id: 9, destination_id: 15, wheelchair: false, aide: false, vision_impaired: true, hearing_impaired: true, recurring: nil, status: "scheduled", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/02/08", pickup_time: "2000-01-01 10:45:00", assigned_by: "Sample Admin", duration: "2 hours", pet: false},
  {member_id: 10, driver_id: 1, origin_id: 10, destination_id: 5, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "complete", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/10", pickup_time: "2000-01-01 11:00:00", assigned_by: "Sample Admin", duration: "1 hour", pet: false},
  {member_id: 9, driver_id: 11, origin_id: 9, destination_id: 15, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "complete", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/11", pickup_time: "2000-01-01 09:30:00", assigned_by: "Sample Admin", duration: "2 hours", pet: false},
  {member_id: 5, driver_id: 12, origin_id: 5, destination_id: 16, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "complete", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/11", pickup_time: "2000-01-01 12:00:00", assigned_by: "Sample Admin", duration: "1.5 hours", pet: false},
  {member_id: 6, driver_id: 5, origin_id: 6, destination_id: 18, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "scheduled", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/14", pickup_time: "2000-01-01 11:00:00", assigned_by: "Sample Admin", duration: "1.5 hours", pet: false},
  {member_id: 2, driver_id: 4, origin_id: 2, destination_id: 9, wheelchair: false, aide: false, vision_impaired: false, hearing_impaired: false, recurring: nil, status: "complete", completion_notes: nil, requested_driver: nil, request_checked: nil, pickup_date: "2016/01/11", pickup_time: "2000-01-01 14:30:00", assigned_by: "Sample Admin", duration: "2 hours", pet: false}
])
